version: '3.7'
services:
  terraform:
    build:
      dockerfile: terraform.Dockerfile
      context: .
    volumes:
      - .:/work
    working_dir: /work
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
